language: r
cache: packages
pandoc_version: 2.5
r_github_packages:
  - leg-ufpr/legtheme
r_packages:
  - xtable
  - printr
  - latticeExtra
  - plyr
  - TeachingDemos
apt_packages:
  - texlive-fonts-recommended
  - texlive-fonts-extra
  - texlive-latex-extra
  - fonts-inconsolata
  - cm-super

before_script:
  - updmap
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
